In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,MinMaxScaler, OrdinalEncoder
import random
pd.set_option('display.max_columns',None)

import warnings
warnings.filterwarnings("ignore")
from sklearn.preprocessing import OrdinalEncoder

import warnings
warnings.filterwarnings("ignore")

# fechas
from datetime import datetime

# gráficos
import seaborn as sns
import matplotlib.pyplot as plt

# preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, Normalizer, MinMaxScaler
from sklearn.preprocessing import PolynomialFeatures

# algoritmos de clasificación
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

# algoritmos de regresión
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet, SGDRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

# métricas
import sklearn.metrics as metrics

# hiperparametrización
from sklearn.model_selection import GridSearchCV

# TensorFlow y tf.keras
import tensorflow as tf
from tensorflow import keras

import xgboost as xgb

from numpy import random
random.seed(42)

from sklearn.model_selection import train_test_split

from sklearn.cluster import KMeans

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Ruta al archivo Parquet 
ruta_archivo = "C:/Users/Herre/Desktop/TFM/Nuclio_EasyMoney/0_Data/clustering_2_result.csv"
# Leer el archivo Parquet 
df_modelo = pd.read_csv(ruta_archivo)

In [ ]:
# Ruta al archivo Parquet 
ruta_archivo = "C:/Users/Herre/Desktop/TFM/Nuclio_EasyMoney/0_Data/df_encoding.csv"
# Leer el archivo Parquet 
df_clustering_2 = pd.read_csv(ruta_archivo)

In [3]:
df_modelo

,salary,loan_amount,debt_to_income_ratio,account_balance,number_of_products,product_engagement_score,age,segment,active_customer,region_code,cluster
0,192902.31,0,0.0,0,0.0,0.0,47,2,0.0,28.0,2
1,2783985.75,0,0.0,0,0.0,0.0,26,1,0.0,41.0,2
2,81755.43,0,0.0,0,0.0,0.0,22,1,0.0,16.0,2
3,81755.43,0,0.0,0,0.0,0.0,22,1,0.0,2.0,2
4,81755.43,0,0.0,0,0.0,0.0,22,1,0.0,8.0,2
...,...,...,...,...,...,...,...,...,...,...,...
445484,67228.32,0,0.0,0,0.0,0.0,22,1,0.0,30.0,6
445485,43249.20,0,0.0,0,1.0,3.0,24,1,0.0,2.0,1
445486,94495.50,0,0.0,0,1.0,3.0,25,1,0.0,13.0,1
445487,177287.82,0,0.0,0,1.0,3.0,22,1,1.0,46.0,1
445488,60823.47,0,0.0,0,1.0,3.0,28,2,1.0,22.0,0

Comentario: Definir Variables Independientes y Dependiente:
Selecciona las variables que vas a utilizar como características (X) y la variable que quieres predecir (y). Aquí, X son todas las columnas excepto la columna objetivo, y y es la columna objetivo.

In [ ]:
X = df_modelo.drop('variable_objetivo', axis=1)  # Reemplaza 'variable_objetivo' con el nombre de tu columna objetivo
y = df_modelo['variable_objetivo']

Fase 2
Dividir los Datos en Conjuntos de Entrenamiento y Prueba:
Divide tus datos en dos conjuntos: uno para entrenar el modelo y otro para probarlo. Usamos un 80% de los datos para el entrenamiento y un 20% para la prueba, pero puedes ajustar este ratio según tus necesidades.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)