# Librerías

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,MinMaxScaler, OrdinalEncoder
import random
pd.set_option('display.max_columns',None)

import warnings
warnings.filterwarnings("ignore")
from sklearn.preprocessing import OrdinalEncoder

import warnings
warnings.filterwarnings("ignore")

# fechas
from datetime import datetime

# gráficos
import seaborn as sns
import matplotlib.pyplot as plt

# preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, Normalizer, MinMaxScaler
from sklearn.preprocessing import PolynomialFeatures

# algoritmos de clasificación
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

# algoritmos de regresión
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet, SGDRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

# métricas
import sklearn.metrics as metrics

# hiperparametrización
from sklearn.model_selection import GridSearchCV

# TensorFlow y tf.keras
import tensorflow as tf
from tensorflow import keras

import xgboost as xgb

from numpy import random
random.seed(42)

from sklearn.model_selection import train_test_split

from sklearn.cluster import KMeans

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, roc_auc_score

In [2]:
# Ruta al archivo 
ruta_archivo = "C:/Users/Herre/Desktop/TFM/Nuclio_EasyMoney/0_Data/df_Clustering.csv"
# Leer el archivo 
df_Modelo = pd.read_csv(ruta_archivo)

In [3]:
df_Modelo

,pk_cid,active_customer,segment,short_term_deposit,loans,mortgage,funds,securities,long_term_deposit,em_account_pp,credit_card,payroll,pension_plan,payroll_account,emc_account,debit_card,em_account_p,em_acount,region_code,age,salary,entry_date_year,entry_date_month,entry_date_day,entry_date_weekday,pk_partition_year,pk_partition_month,pk_partition_day,pk_partition_weekday,entry_channel_KFC,entry_channel_KHE,entry_channel_KHQ,entry_channel_Otros,country_id_ES,gender_V,deceased_S,number_of_products,account_balance,loan_amount,product_engagement_score,debt_to_income_ratio,cluster
0,1297423,0.0,2,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,28.0,47,192902.31,2017,8,18,4,2018,7,28,5,0,0,0,1,1,0,0,0.0,0,0,0.0,0.0,6
1,1087842,0.0,1,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,41.0,26,2783985.75,2015,10,24,5,2018,7,28,5,0,1,0,0,1,0,0,0.0,0,0,0.0,0.0,4
2,1147514,0.0,1,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,16.0,22,81755.43,2016,7,25,0,2018,7,28,5,0,1,0,0,1,0,0,0.0,0,0,0.0,0.0,1
3,1147863,0.0,1,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,2.0,22,81755.43,2016,7,25,0,2018,7,28,5,0,1,0,0,1,0,0,0.0,0,0,0.0,0.0,1
4,1147587,0.0,1,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,8.0,22,81755.43,2016,7,25,0,2018,7,28,5,0,1,0,0,1,1,0,0.0,0,0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445484,1164494,0.0,1,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,30.0,22,67228.32,2016,8,13,5,2019,5,28,1,0,1,0,0,1,0,0,0.0,0,0,0.0,0.0,1
445485,1164521,0.0,1,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,1,2.0,24,43249.20,2016,8,13,5,2019,5,28,1,0,1,0,0,1,1,0,1.0,0,0,3.0,0.0,1
445486,1164462,0.0,1,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,1,13.0,25,94495.50,2016,8,13,5,2019,5,28,1,0,1,0,0,1,0,0,1.0,0,0,3.0,0.0,1
445487,1164587,1.0,1,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,1,46.0,22,177287.82,2016,8,13,5,2019,5,28,1,0,1,0,0,1,1,0,1.0,0,0,3.0,0.0,1
445488,1489273,1.0,2,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,1,22.0,28,60823.47,2018,10,24,2,2019,5,28,1,0,0,0,1,1,1,0,1.0,0,0,3.0,0.0,0

## Dividir datos

In [ ]:
# Dividir el dataframe en 70% para entrenamiento y 30% para predicción
df_entrenar, df_predecir = train_test_split(df_Modelo, test_size=0.3, random_state=42)

In [ ]:
df_entrenar

In [ ]:
df_predecir

In [ ]:
AGRUPO POR PRODUCTOS
COLUMANS IMPORTANTES
NO HACE FALTA LA INFO DE LOS CLUSTER

## Features importantes

In [ ]:
#feature importance
params = {'random_state': 42, 'n_jobs': 4, 'n_estimators': 100, 'max_depth': 4}
# se entrena un RandomForest y se plotean las variables que tuvieron más importancia en el modelo
y = df_entrenar['cluster']
x = df_entrenar.drop('cluster' ,axis=1)
# entrena un RandomForest Classifier
clf = RandomForestClassifier(**params)
clf = clf.fit(x, y)
# Plotea las 10 mejores Features importances
features = clf.feature_importances_[:10]
columnas = x.columns[:10]
imp = pd.Series(data=features, index=columnas).sort_values(ascending=False)
plt.figure(figsize=(10,8))
plt.title("Feature importance")
ax = sns.barplot(y=imp.index, x=imp.values, palette="Blues_d", orient='h')
plt.show()

# Split X-y

In [ ]:
# se guarda un 30% de datos para el test y un 70% para el train
y = df_entrenar['AHORRO']
X = df_entrenar.drop('AHORRO', axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

## Estandarización

In [ ]:
# se estandarizan las variables para evitar sesgo
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)   # estandariza y define la regla de estandarización
X_test = scaler.transform(X_test)         # estandariza según la regla definida con el X_train

In [ ]:
X_train.shape

In [ ]:
f1s = pd.DataFrame(columns=['modelo', 'f1_score'])
f1s

## Clasificación Multiclase

In [ ]:
# añadimos en una lista los modelos que queremos poner a competir

modelos = []
modelos.append(('SVC', SVC()))
modelos.append(('LogisticRegression', LogisticRegression()))
modelos.append(('RidgeClassifier', RidgeClassifier()))
modelos.append(('DecisionTreeClassifier', DecisionTreeClassifier()))
modelos.append(('RandomForestClassifier', RandomForestClassifier()))
modelos.append(('GradientBoostingClassifier', GradientBoostingClassifier()))
modelos.append(('XGBClassifier', XGBClassifier()))
modelos.append(('CatBoostClassifier', CatBoostClassifier(verbose=False)))

In [ ]:
for nombre, modelo in modelos:
  # entrenamiento
  modelo.fit(X_train, y_train)

  # predicción del test
  y_pred = modelo.predict(X_test)

  # evalua la metrica
  f1_score = metrics.f1_score(y_test, y_pred, average='macro')
  #el average='macro' se usa cuando estamos haciendo modelos multiclases. Sino lo pones el modelo peta.

  # añade la métrica al dataframe de métricas
  metrica = pd.DataFrame({'modelo':[nombre], 'f1_score':[f1_score]})

  print(nombre, np.round(f1_score,5))

  f1s = pd.concat([f1s,metrica], ignore_index=True)

In [ ]:
f1s.sort_values('f1_score', ascending= False)

# Predicción

In [ ]:
df_predecir.drop(columns=['AHORRO'], inplace=True)

In [ ]:
# se estandarizan las variables del dataset a predecir según la regla definida con el X_train
X_predecir = scaler.transform(df_predecir)

In [ ]:
# definimos el modelo
modelo = GradientBoostingClassifier()

# entrenamiento
modelo.fit(X_train, y_train)

# predicción de las observaciones a predecir
y_pred = modelo.predict(X_predecir)

# añadimos la predicción al dataframe a predecir
df_predecir['AHORRO'] = y_pred

# redeondeamos las predicciones
df_predecir['AHORRO'] = round(df_predecir['AHORRO'], 0)

# cambiamos los valores extremos
df_predecir['AHORRO'] = df_predecir['AHORRO'].apply(lambda x: 0 if x < 0
                                                                      else (5 if x > 5
                                                                            else int(x)))

In [ ]:
len (df_predecir)

In [ ]:
df_predecir.head()

In [ ]:
PROBABILIDAD * INGRESO DE ESE PRODUCTO

SKLEARN PREDICT PRO_BA ME VA A DAR LA PROBABILIDAD DE QUE SE HAGA UNA COSA O LA OTRA

LA CONDICIÓN DE QUE NO PORQUE TENGA HIPOTECA LA VA A VOLVER A COMPRAR: CUANTOS PRODUCTOS DE LA CATEGORIA X -1

In [ ]:
df_Modelo.head()