# Librerias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,MinMaxScaler, OrdinalEncoder
import random
pd.set_option('display.max_columns',None)

import warnings
warnings.filterwarnings("ignore")
from sklearn.preprocessing import OrdinalEncoder

import warnings
warnings.filterwarnings("ignore")

# fechas
from datetime import datetime

# gráficos
import seaborn as sns
import matplotlib.pyplot as plt

# preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, Normalizer, MinMaxScaler
from sklearn.preprocessing import PolynomialFeatures

# algoritmos de clasificación
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

# algoritmos de regresión
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet, SGDRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

# métricas
import sklearn.metrics as metrics

# hiperparametrización
from sklearn.model_selection import GridSearchCV

# TensorFlow y tf.keras
import tensorflow as tf
from tensorflow import keras

import xgboost as xgb

from numpy import random
random.seed(42)

from sklearn.model_selection import train_test_split

In [2]:
file_path = "C:/Users/Herre/Desktop/TFM/Data/df_final.csv"

In [3]:
df_encoding = pd.read_csv(file_path)

In [4]:
df_encoding

,pk_cid,pk_partition_merged,entry_date,entry_channel,active_customer,segment,short_term_deposit,loans,mortgage,funds,securities,long_term_deposit,em_account_pp,credit_card,payroll,pension_plan,payroll_account,emc_account,debit_card,em_account_p,em_acount,pk_partition_social,country_id,region_code,gender,age,deceased,salary
0,1298102,2018-07-28,2017-08-21,KAT,0.0,Unknown,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,2018-07-28,ES,35.0,V,26-35,N,NaN
1,1297423,2018-07-28,2017-08-18,KAT,0.0,02 - PARTICULARES,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,2018-07-28,ES,28.0,H,46-65,N,NaN
2,1299811,2018-07-28,2017-08-29,KHE,0.0,03 - UNIVERSITARIO,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,2018-07-28,ES,26.0,V,18-25,N,NaN
3,1299907,2018-07-28,2017-08-29,KHE,0.0,03 - UNIVERSITARIO,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,2018-07-28,ES,39.0,V,18-25,N,NaN
4,1299380,2018-07-28,2017-08-27,KAT,0.0,01 - TOP,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,2018-07-28,ES,28.0,H,36-45,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454746,1490985,2019-05-28,2018-10-27,KHQ,1.0,03 - UNIVERSITARIO,0,0,0,0,0,0,0,0,1.0,1.0,1,0,1,0,0,2019-05-28,ES,8.0,H,26-35,N,NaN
454747,1490986,2019-05-28,2018-10-27,KHM,1.0,02 - PARTICULARES,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,1,2019-05-28,ES,8.0,H,46-65,N,NaN
454748,1490987,2019-05-28,2018-10-27,KHQ,1.0,03 - UNIVERSITARIO,0,0,0,0,0,0,0,0,0.0,1.0,1,0,0,0,0,2019-05-28,ES,33.0,V,18-25,N,NaN
454749,1490991,2019-05-28,2018-10-27,KHQ,0.0,03 - UNIVERSITARIO,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,2019-05-28,ES,28.0,H,18-25,N,NaN
454750,1550586,2019-05-28,2019-05-13,KHE,1.0,Unknown,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,1,2019-05-28,ES,28.0,H,36-45,N,NaN

In [5]:
df_encoding.isnull().sum()

pk_cid                      0
pk_partition_merged         0
entry_date                  0
entry_channel               0
active_customer             0
segment                     0
short_term_deposit          0
loans                       0
mortgage                    0
funds                       0
securities                  0
long_term_deposit           0
em_account_pp               0
credit_card                 0
payroll                     0
pension_plan                0
payroll_account             0
emc_account                 0
debit_card                  0
em_account_p                0
em_acount                   0
pk_partition_social         0
country_id                  0
region_code                 0
gender                      0
age                         0
deceased                    0
salary                 155402
dtype: int64

In [6]:
#Antes de hacer Encoding vamos a eliminar los nulos de la columna "salary" porque hay demasiados.
df_encoding = df_encoding.dropna(subset=['salary'])

In [7]:
df_encoding.head()

,pk_cid,pk_partition_merged,entry_date,entry_channel,active_customer,segment,short_term_deposit,loans,mortgage,funds,securities,long_term_deposit,em_account_pp,credit_card,payroll,pension_plan,payroll_account,emc_account,debit_card,em_account_p,em_acount,pk_partition_social,country_id,region_code,gender,age,deceased,salary
1881,1076016,2018-09-28,2015-10-05,KHE,1.0,03 - UNIVERSITARIO,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,2018-09-28,ES,41.0,H,26-35,N,130009.98
1883,1075994,2018-09-28,2015-10-05,KHE,0.0,03 - UNIVERSITARIO,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,2018-09-28,ES,41.0,H,26-35,N,97498.50
1892,1085344,2018-09-28,2015-10-22,KHE,0.0,02 - PARTICULARES,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,2018-09-28,ES,41.0,H,46-65,N,362560.02
1895,1087187,2018-09-28,2015-10-24,KHE,0.0,03 - UNIVERSITARIO,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,2018-09-28,ES,15.0,V,18-25,N,27535.77
1897,1064230,2018-09-28,2015-09-20,KHE,0.0,03 - UNIVERSITARIO,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,2018-09-28,ES,50.0,V,26-35,N,2783985.75

In [8]:
df_encoding["segment"].unique()

array(['03 - UNIVERSITARIO', '02 - PARTICULARES', '01 - TOP', 'Unknown'],
      dtype=object)

In [9]:
#Eliminamos esa columna porque está duplicada
df_encoding.drop(columns=['pk_partition_social'], inplace=True)

In [10]:
df_encoding = df_encoding.rename(columns={'pk_partition_merged': 'pk_partition'})
#Cambiamos el nombre de la columna para dejar el nombre estandar de antes

# One Hot Encoding

In [11]:
columnas_ohe = ["entry_channel", "active_customer", "short_term_deposit", "loans", "mortgage", "funds", "securities", "long_term_deposit", "credit_card", "payroll", "pension_plan", "payroll_account", "emc_account", "debit_card", "em_account_p", "em_acount", "country_id", "region_code", "gender", "age", "deceased"]

In [12]:
# Convertir las variables categóricas en variables dummy
df_encoding = pd.get_dummies(data=df_encoding, columns=columnas_ohe, dtype=int)

In [13]:
df_encoding

,pk_cid,pk_partition,entry_date,segment,em_account_pp,salary,entry_channel_KAT,entry_channel_KFC,entry_channel_KHE,entry_channel_KHK,entry_channel_KHM,entry_channel_KHQ,entry_channel_Otros,active_customer_0.0,active_customer_1.0,short_term_deposit_0,short_term_deposit_1,loans_0,loans_1,mortgage_0,mortgage_1,funds_0,funds_1,securities_0,securities_1,long_term_deposit_0,long_term_deposit_1,credit_card_0,credit_card_1,payroll_0.0,payroll_1.0,pension_plan_0.0,pension_plan_1.0,payroll_account_0,payroll_account_1,emc_account_0,emc_account_1,debit_card_0,debit_card_1,em_account_p_0,em_account_p_1,em_acount_0,em_acount_1,country_id_ES,region_code_1.0,region_code_2.0,region_code_3.0,region_code_4.0,region_code_5.0,region_code_6.0,region_code_7.0,region_code_8.0,region_code_9.0,region_code_10.0,region_code_11.0,region_code_12.0,region_code_13.0,region_code_14.0,region_code_15.0,region_code_16.0,region_code_17.0,region_code_18.0,region_code_19.0,region_code_20.0,region_code_21.0,region_code_22.0,region_code_23.0,region_code_24.0,region_code_25.0,region_code_26.0,region_code_27.0,region_code_28.0,region_code_29.0,region_code_30.0,region_code_31.0,region_code_32.0,region_code_33.0,region_code_34.0,region_code_35.0,region_code_36.0,region_code_37.0,region_code_38.0,region_code_39.0,region_code_40.0,region_code_41.0,region_code_42.0,region_code_43.0,region_code_44.0,region_code_45.0,region_code_46.0,region_code_47.0,region_code_48.0,region_code_49.0,region_code_50.0,region_code_51.0,region_code_52.0,gender_H,gender_V,age_0-17,age_18-25,age_26-35,age_36-45,age_46-65,age_66-110,deceased_N,deceased_S
1881,1076016,2018-09-28,2015-10-05,03 - UNIVERSITARIO,0,130009.98,0,0,1,0,0,0,0,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0
1883,1075994,2018-09-28,2015-10-05,03 - UNIVERSITARIO,0,97498.50,0,0,1,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0
1892,1085344,2018-09-28,2015-10-22,02 - PARTICULARES,0,362560.02,0,0,1,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0
1895,1087187,2018-09-28,2015-10-24,03 - UNIVERSITARIO,0,27535.77,0,0,1,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0
1897,1064230,2018-09-28,2015-09-20,03 - UNIVERSITARIO,0,2783985.75,0,0,1,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427142,1314665,2019-05-28,2017-09-23,02 - PARTICULARES,0,111435.36,0,1,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,1,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,1,0
427143,1314667,2019-05-28,2017-09-23,02 - PARTICULARES,0,41553.57,0,1,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0
427144,1314668,2019-05-28,2017-09-23,03 - UNIVERSITARIO,0,135522.15,0,0,1,0,0,0,0,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0
427145,1314669,2019-05-28,2017-09-23,02 - PARTICULARES,0,127411.35,0,1,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0
440948,1304388,2019-05-28,2017-09-09,02 - PARTICULARES,0,106366.68,0,1,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0

#### respecto a las fechas podriamos quedarnos con año y mes y quitar los guiones entre medias, dejarlo como un solo string y luego pasarlo a int.

#### quitar las columnas de fechas y recuperarlas despues de la segmentación para pdoer proyectarlas en el PowerBI

## Borrar columnas duales

In [14]:
columnas_duales = ["active_customer_0.0", "short_term_deposit_0", "loans_0", "mortgage_0", "funds_0", "securities_0", "long_term_deposit_0", "credit_card_0", "payroll_0.0", "pension_plan_0.0", "payroll_account_0","emc_account_0", "debit_card_0", "em_account_p_0", "em_acount_0", "region_code_52.0", "gender_H", "deceased_N", "age_66-110"]

In [15]:
# Eliminar las columnas especificadas
df_encoding.drop(columns=columnas_duales, inplace=True)

# Ordinal Encoding

In [16]:
from sklearn.preprocessing import LabelEncoder,MinMaxScaler, OrdinalEncoder

In [17]:
# Crear un diccionario para el mapeo de valores
ordinal_mapping = {
    'Unknown': 0,
    '03 - UNIVERSITARIO': 1,
    '02 - PARTICULARES': 2,
    '01 - TOP': 3
}

# Aplicar el mapeo a la columna 'segment'
df_encoding['segment'] = df_encoding['segment'].map(ordinal_mapping)

In [18]:
df_encoding

,pk_cid,pk_partition,entry_date,segment,em_account_pp,salary,entry_channel_KAT,entry_channel_KFC,entry_channel_KHE,entry_channel_KHK,entry_channel_KHM,entry_channel_KHQ,entry_channel_Otros,active_customer_1.0,short_term_deposit_1,loans_1,mortgage_1,funds_1,securities_1,long_term_deposit_1,credit_card_1,payroll_1.0,pension_plan_1.0,payroll_account_1,emc_account_1,debit_card_1,em_account_p_1,em_acount_1,country_id_ES,region_code_1.0,region_code_2.0,region_code_3.0,region_code_4.0,region_code_5.0,region_code_6.0,region_code_7.0,region_code_8.0,region_code_9.0,region_code_10.0,region_code_11.0,region_code_12.0,region_code_13.0,region_code_14.0,region_code_15.0,region_code_16.0,region_code_17.0,region_code_18.0,region_code_19.0,region_code_20.0,region_code_21.0,region_code_22.0,region_code_23.0,region_code_24.0,region_code_25.0,region_code_26.0,region_code_27.0,region_code_28.0,region_code_29.0,region_code_30.0,region_code_31.0,region_code_32.0,region_code_33.0,region_code_34.0,region_code_35.0,region_code_36.0,region_code_37.0,region_code_38.0,region_code_39.0,region_code_40.0,region_code_41.0,region_code_42.0,region_code_43.0,region_code_44.0,region_code_45.0,region_code_46.0,region_code_47.0,region_code_48.0,region_code_49.0,region_code_50.0,region_code_51.0,gender_V,age_0-17,age_18-25,age_26-35,age_36-45,age_46-65,deceased_S
1881,1076016,2018-09-28,2015-10-05,1,0,130009.98,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1883,1075994,2018-09-28,2015-10-05,1,0,97498.50,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1892,1085344,2018-09-28,2015-10-22,2,0,362560.02,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1895,1087187,2018-09-28,2015-10-24,1,0,27535.77,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0
1897,1064230,2018-09-28,2015-09-20,1,0,2783985.75,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427142,1314665,2019-05-28,2017-09-23,2,0,111435.36,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0
427143,1314667,2019-05-28,2017-09-23,2,0,41553.57,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
427144,1314668,2019-05-28,2017-09-23,1,0,135522.15,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
427145,1314669,2019-05-28,2017-09-23,2,0,127411.35,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0
440948,1304388,2019-05-28,2017-09-09,2,0,106366.68,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

### Una vez hemos hecho todo esto ya no tenemos columnas categóricas en todo el dataframe, solo nos quedan las fechas.

# Exportamos el archivo para pasar a la segmentación

In [19]:
# Guardar resultados
df_encoding.to_csv('df_encoding.csv', index=False)